# Site settings
title: GROW
version: "v1"
description: "GROW"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Tachyons Version
tv: "4.7.4"

# Build settings
markdown: kramdown

# Exclude this stuff
exclude: [node_modules, gulpfile.js]